version: '3'
services:
    client:
        image: 'qianwei22/multi-client-10-14'
        mem_limit: 128m
        hostname: client
    server:
        image: 'qianwei22/multi-server-10-14'
        mem_limit: 128m
        hostname: api
        environment:
            - REDIS_HOST=$REDIS_HOST
            - REDIS_PORT=$REDIS_PORT
            - PGUSER=$PGUSER
            - PGHOST=$PGHOST
            - PGDATABASE=$PGDATABASE
            - PGPASSWORD=$PGPASSWORD
            - PGPORT=$PGPORT
    worker:
        image: 'qianwei22/multi-worker-10-14'
        mem_limit: 128m
        hostname: worker
        environment:
            - REDIS_HOST=$REDIS_HOST
            - REDIS_PORT=$REDIS_PORT
    nginx:
        image: 'qianwei22/multi-nginx-10-14'
        mem_limit: 128m
        hostname: nginx
        ports:
            - '80:80'
